version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 irnuscrawler.asgi -k uvicorn.workers.UvicornWorker
    volumes:
      - .:/usr/src/app/
      - static_volume:/usr/src/app/static
    ports:
      - 8000

  nginx:
    image: nginx:1.17
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/home/app/web/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/fullchain.pem:/certificates/fullchain.pem:ro
      - ./nginx/privkey.pem:/certificates/privkey.pem:ro
    depends_on:
      - web

volumes:
  static_volume:
